# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b53148a4a96e727a51234f33dccdcde0d2f47a779af0a2ef7d1412747727a537bda3a033e367926db94adba22efc6539b871dfd08974cf65bd462313072b20aa

test:
  secret_key_base: fe6af6fc72f1f3891fbab2e216050d29356ee91ab9c579f9b36f65140539e84a18b43c14fa034db0603ea565f72a5fe8c8cb98a788187e4d9e1c764a5f2c1dd2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
